# Generated by Django 2.1.4 on 2019-03-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_civil', models.CharField(max_length=150, verbose_name='Nome Civil')),
                ('nome_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Social')),
                ('nome_apresentacao', models.CharField(max_length=150, verbose_name='Nome de Apresentação')),
                ('nome_usual', models.CharField(max_length=150, verbose_name='Nome Usual')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(max_length=150, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(max_length=150, verbose_name='Nome do Pai')),
                ('sexo', models.PositiveIntegerField(choices=[(1, 'Feminino'), (2, 'Masculino')], verbose_name='Sexo')),
                ('rg', models.PositiveIntegerField(verbose_name='RG')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('estado_emissao', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RN', max_length=2, verbose_name='Estado Emissão')),
                ('orgao_rg', models.CharField(max_length=100, verbose_name='Órgão do RG')),
                ('telefone', models.CharField(max_length=150, verbose_name='Telefone')),
                ('pais_nascimento', models.CharField(max_length=100, verbose_name='País de Nascimento')),
                ('estado_nascimento', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RN', max_length=2, verbose_name='Estado de Nascimento')),
                ('cidade_nascimento', models.CharField(max_length=150, verbose_name='Município de Nascimento')),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('complemento', models.CharField(max_length=100, null=True, verbose_name='Complento')),
                ('uf', models.CharField(max_length=100, verbose_name='UF')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo')),
            ],
        ),
    ]
