# Generated by Django 2.1.7 on 2019-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_auto_20190508_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='inscricao/media/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
    ]
