# Generated by Django 2.1.7 on 2019-06-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_auto_20190604_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='documento',
        ),
        migrations.AddField(
            model_name='documento',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscricao.Candidato'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
