# Generated by Django 2.1.1 on 2018-11-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Discente/Bolsista', max_length=100, verbose_name='Tipo')),
                ('programa', models.CharField(max_length=100, verbose_name='Programa')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('siglaUO', models.CharField(help_text='Ex.: DG-EAD/IFRN', max_length=100, verbose_name='Unidade organizacional')),
                ('linkEdital', models.URLField(help_text='Informe o LINK onde está o edital', max_length=300, verbose_name='URL')),
                ('grupo', models.CharField(max_length=200, null=True, verbose_name='Grupo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('ano', models.PositiveIntegerField(help_text='Digite o ano', verbose_name='Ano')),
                ('periodo', models.PositiveIntegerField(choices=[(1, '1º Período'), (2, '2º Período')], verbose_name='Período letivo')),
                ('data_publicacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existe_taxa', models.BooleanField(default=False)),
                ('valor_taxa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vencimento_boleto', models.DateField()),
                ('edital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Edital')),
            ],
        ),
    ]
