# Generated by Django 2.1.1 on 2018-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEdital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200, verbose_name='Tipo')),
                ('vaga', models.CharField(max_length=100, verbose_name='Tipo')),
                ('numero_vagas', models.IntegerField()),
            ],
        ),
    ]
