# Generated by Django 2.1.1 on 2018-12-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEdital', '0002_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo_classificacao', models.PositiveIntegerField(choices=[(1, 'Eliminatória'), (2, 'Classificatória')], verbose_name='Tipo de Classificação')),
                ('aproveitamento_min', models.PositiveIntegerField(help_text='Nota necessária para passar', verbose_name='Aproveitamento Mínimo')),
                ('fator_habilitacao', models.PositiveIntegerField(help_text='Quantidade máxima de cadidatos que serão selecionados', verbose_name='Fator Habilitação')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Edital')),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='edital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Edital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='curso',
            field=models.CharField(max_length=200, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='numero_vagas',
            field=models.IntegerField(verbose_name='Número de vagas'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='vaga',
            field=models.CharField(max_length=100, verbose_name='Vaga'),
        ),
    ]
