# Generated by Django 2.1.1 on 2018-12-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEdital', '0004_auto_20181206_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Fase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Nome')),
                ('nota_minima', models.FloatField(verbose_name='Nota Mínima')),
                ('nota_maxima', models.FloatField(verbose_name='Nota Maxima')),
                ('ajuda_avaliador', models.CharField(max_length=500, verbose_name='Nome')),
                ('incremento_nota', models.IntegerField(verbose_name='Incremento da Nota')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Fase')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=200, verbose_name='Etapa')),
                ('marco', models.CharField(max_length=200, verbose_name='Marco')),
                ('inicio', models.DateField(verbose_name='Data Inicial')),
                ('fim', models.DateField(verbose_name='Data Final')),
                ('fase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Fase')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Fase')),
            ],
        ),
    ]
