# Generated by Django 2.1.1 on 2018-12-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroEdital', '0005_avaliador_criterioavaliacao_cronograma_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrategiaClassificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriaco', models.CharField(help_text='Exemplo: Inscrição sem anexos', max_length=200, verbose_name='Descrição')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Fase')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoNotaZero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriaco', models.CharField(help_text='Exemplo: Inscrição sem anexos', max_length=200, verbose_name='Descrição')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastroEdital.Fase')),
            ],
        ),
    ]
